# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update README

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    paths:
      - scripts/README.template.md
      - scripts/update.js
      - LICENSE
      - package.json
      - package-lock.json

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 20.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run update
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.1
      with:
        add: README.md
        message: 'Updating README'
      env:
        GITHUB_TOKEN: ${{secrets.PERSONAL_SECRET_TOKEN}}
